name: dart_practice
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {equatable: ^2.0.5, freezed_annotation: ^2.4.1, json_annotation: ^4.8.1}
